services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: argus-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: argus-postgres
    environment:
      POSTGRES_USER: argus
      POSTGRES_PASSWORD: password
      POSTGRES_DB: argus_db
    ports:
      - "5432:5432"
    volumes:
      - argus-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U argus -d argus_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  argus-postgres-data:
    driver: local
