server:
  port: 8083

spring:
  application:
    name: query-api
  datasource:
    url: jdbc:postgresql://localhost:5432/argus_db
    username: argus
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate